### ISSUE TITLE
Not working with TypeScript version >2.6

### ISSUE THREAD

**Issue by DanielKucal** [DanielKucal/ts-debug#1]
Interface `Console` has changed in newest TypeScript version and this library needs an update.
```
ERROR in node_modules/ts-debug/debug.d.ts(1,22): error TS2420: Class 'Debugger' incorrectly implements interface 'Console'.
  Property 'memory' is missing in type 'Debugger'.
```
